#!/bin/sh
set -e

if [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi
if [ "$1" = purge ] && [ -x /usr/bin/deb-systemd-helper ]; then
    deb-systemd-helper purge dnp3-bridge.service >/dev/null || true
fi
